### ISSUE TITLE
ability to install attic against a flake.lock file

### ISSUE THREAD

**Issue by isabelroses** [ryanccn/attic-action#28]
Should be possible with `nix profile install --inputs-from ./path/to/flake.lock nixpkgs#attic-client`.

**Comment by antifuchs** [comment]
I have wanted to do this too and thanks to the is-installed check in this action, it's possible to do that (and get the client cached, too):

```yml
    - name: "Restore attic-client binary"
      uses: actions/cache@v4
      id: attic-cache
      with:
        path: /tmp/attic-client
        key: attic-client-${{runner.os}}-${{ hashFiles(format('{0}/flake.lock', inputs.root)) }}
    - name: "Make attic-client binary cacheable"
      if: steps.attic-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        nix copy --to file:///tmp/attic-client --inputs-from ${{inputs.root}} nixpkgs#attic-client
    - name: "Install attic-client binary"
      shell: bash
      run: |
        # https://git.lix.systems/lix-project/lix/issues/751:
        find /tmp/attic-client -type f -print0 | xargs -0 touch -d '@0'

        nix copy --inputs-from ${{inputs.root}} --from file:///tmp/attic-client nixpkgs#attic-client
        nix profile install --inputs-from ${{inputs.root}} nixpkgs#attic-client
    - uses: ryanccn/attic-action@v0
```

(That's from an action that takes a `root` parameter, you can probably simplify this away if your flake.nix/flake.lock always live in the repo root.)

With the above entries, the workflow will install the exact attic-client that's pinned in flake.lock, as well as cache the attic client and its dependencies (saving about 20-30s of test setup time, depending on how fast cache.nixos.org is at any given time)
